-- Seed data: common S&P 500 tickers with sectors
-- Run once after migrations: psql $DATABASE_URL -f seeds/tickers_seed.sql

INSERT INTO tickers (symbol, sector, company_name) VALUES
  ('AAPL',  'Technology',             'Apple Inc.'),
  ('MSFT',  'Technology',             'Microsoft Corporation'),
  ('GOOGL', 'Technology',             'Alphabet Inc.'),
  ('AMZN',  'Consumer Discretionary','Amazon.com Inc.'),
  ('NVDA',  'Technology',             'NVIDIA Corporation'),
  ('META',  'Technology',             'Meta Platforms Inc.'),
  ('TSLA',  'Consumer Discretionary','Tesla Inc.'),
  ('BRK',   'Financials',             'Berkshire Hathaway Inc.'),
  ('LLY',   'Healthcare',             'Eli Lilly and Company'),
  ('JPM',   'Financials',             'JPMorgan Chase & Co.'),
  ('V',     'Financials',             'Visa Inc.'),
  ('UNH',   'Healthcare',             'UnitedHealth Group'),
  ('XOM',   'Energy',                 'Exxon Mobil Corporation'),
  ('JNJ',   'Healthcare',             'Johnson & Johnson'),
  ('MA',    'Financials',             'Mastercard Incorporated'),
  ('PG',    'Consumer Staples',       'Procter & Gamble Co.'),
  ('HD',    'Consumer Discretionary','Home Depot Inc.'),
  ('CVX',   'Energy',                 'Chevron Corporation'),
  ('MRK',   'Healthcare',             'Merck & Co. Inc.'),
  ('ABBV',  'Healthcare',             'AbbVie Inc.'),
  ('KO',    'Consumer Staples',       'The Coca-Cola Company'),
  ('PEP',   'Consumer Staples',       'PepsiCo Inc.'),
  ('AVGO',  'Technology',             'Broadcom Inc.'),
  ('COST',  'Consumer Staples',       'Costco Wholesale Corporation'),
  ('MCD',   'Consumer Discretionary','McDonald''s Corporation'),
  ('CSCO',  'Technology',             'Cisco Systems Inc.'),
  ('WMT',   'Consumer Staples',       'Walmart Inc.'),
  ('ACN',   'Technology',             'Accenture plc'),
  ('ABT',   'Healthcare',             'Abbott Laboratories'),
  ('CRM',   'Technology',             'Salesforce Inc.'),
  ('BAC',   'Financials',             'Bank of America Corp.'),
  ('ORCL',  'Technology',             'Oracle Corporation'),
  ('AMD',   'Technology',             'Advanced Micro Devices Inc.'),
  ('INTC',  'Technology',             'Intel Corporation'),
  ('NFLX',  'Communication Services','Netflix Inc.'),
  ('DIS',   'Communication Services','The Walt Disney Company'),
  ('GS',    'Financials',             'Goldman Sachs Group Inc.'),
  ('MS',    'Financials',             'Morgan Stanley'),
  ('GE',    'Industrials',            'General Electric Company'),
  ('F',     'Consumer Discretionary','Ford Motor Company'),
  ('GM',    'Consumer Discretionary','General Motors Company'),
  ('BA',    'Industrials',            'Boeing Company'),
  ('CAT',   'Industrials',            'Caterpillar Inc.'),
  ('MMM',   'Industrials',            '3M Company'),
  ('DE',    'Industrials',            'Deere & Company'),
  ('UPS',   'Industrials',            'United Parcel Service Inc.'),
  ('FDX',   'Industrials',            'FedEx Corporation'),
  ('AMT',   'Real Estate',            'American Tower Corporation'),
  ('NEE',   'Utilities',              'NextEra Energy Inc.'),
  ('LIN',   'Materials',              'Linde plc')
ON CONFLICT (symbol) DO NOTHING;
