-- Seed data: S&P 500 tickers with sectors
-- Run once after migrations: psql $DATABASE_URL -f seeds/tickers_seed.sql

INSERT INTO tickers (symbol, sector, company_name) VALUES
  ('MMM', 'Industrials', '3M'),
  ('AOS', 'Industrials', 'A. O. Smith'),
  ('ABT', 'Healthcare', 'Abbott Laboratories'),
  ('ABBV', 'Healthcare', 'AbbVie'),
  ('ACN', 'Technology', 'Accenture'),
  ('ADBE', 'Technology', 'Adobe Inc.'),
  ('AMD', 'Technology', 'Advanced Micro Devices'),
  ('AES', 'Utilities', 'AES Corporation'),
  ('AFL', 'Financials', 'Aflac'),
  ('A', 'Healthcare', 'Agilent Technologies'),
  ('APD', 'Materials', 'Air Products'),
  ('ABNB', 'Consumer Discretionary', 'Airbnb'),
  ('AKAM', 'Technology', 'Akamai Technologies'),
  ('ALB', 'Materials', 'Albemarle Corporation'),
  ('ARE', 'Real Estate', 'Alexandria Real Estate Equities'),
  ('ALGN', 'Healthcare', 'Align Technology'),
  ('ALLE', 'Industrials', 'Allegion'),
  ('LNT', 'Utilities', 'Alliant Energy'),
  ('ALL', 'Financials', 'Allstate'),
  ('GOOGL', 'Communication Services', 'Alphabet Inc. (Class A)'),
  ('GOOG', 'Communication Services', 'Alphabet Inc. (Class C)'),
  ('MO', 'Consumer Staples', 'Altria'),
  ('AMZN', 'Consumer Discretionary', 'Amazon'),
  ('AMCR', 'Materials', 'Amcor'),
  ('AEE', 'Utilities', 'Ameren'),
  ('AEP', 'Utilities', 'American Electric Power'),
  ('AXP', 'Financials', 'American Express'),
  ('AIG', 'Financials', 'American International Group'),
  ('AMT', 'Real Estate', 'American Tower'),
  ('AWK', 'Utilities', 'American Water Works'),
  ('AMP', 'Financials', 'Ameriprise Financial'),
  ('AME', 'Industrials', 'Ametek'),
  ('AMGN', 'Healthcare', 'Amgen'),
  ('APH', 'Technology', 'Amphenol'),
  ('ADI', 'Technology', 'Analog Devices'),
  ('AON', 'Financials', 'Aon plc'),
  ('APA', 'Energy', 'APA Corporation'),
  ('APO', 'Financials', 'Apollo Global Management'),
  ('AAPL', 'Technology', 'Apple Inc.'),
  ('AMAT', 'Technology', 'Applied Materials'),
  ('APP', 'Technology', 'AppLovin'),
  ('APTV', 'Consumer Discretionary', 'Aptiv'),
  ('ACGL', 'Financials', 'Arch Capital Group'),
  ('ADM', 'Consumer Staples', 'Archer Daniels Midland'),
  ('ARES', 'Financials', 'Ares Management'),
  ('ANET', 'Technology', 'Arista Networks'),
  ('AJG', 'Financials', 'Arthur J. Gallagher & Co.'),
  ('AIZ', 'Financials', 'Assurant'),
  ('T', 'Communication Services', 'AT&T'),
  ('ATO', 'Utilities', 'Atmos Energy'),
  ('ADSK', 'Technology', 'Autodesk'),
  ('ADP', 'Industrials', 'Automatic Data Processing'),
  ('AZO', 'Consumer Discretionary', 'AutoZone'),
  ('AVB', 'Real Estate', 'AvalonBay Communities'),
  ('AVY', 'Materials', 'Avery Dennison'),
  ('AXON', 'Industrials', 'Axon Enterprise'),
  ('BKR', 'Energy', 'Baker Hughes'),
  ('BALL', 'Materials', 'Ball Corporation'),
  ('BAC', 'Financials', 'Bank of America'),
  ('BAX', 'Healthcare', 'Baxter International'),
  ('BDX', 'Healthcare', 'Becton Dickinson'),
  ('BBY', 'Consumer Discretionary', 'Best Buy'),
  ('TECH', 'Healthcare', 'Bio-Techne'),
  ('BIIB', 'Healthcare', 'Biogen'),
  ('BLK', 'Financials', 'BlackRock'),
  ('BX', 'Financials', 'Blackstone Inc.'),
  ('XYZ', 'Financials', 'Block, Inc.'),
  ('BK', 'Financials', 'BNY Mellon'),
  ('BA', 'Industrials', 'Boeing'),
  ('BKNG', 'Consumer Discretionary', 'Booking Holdings'),
  ('BSX', 'Healthcare', 'Boston Scientific'),
  ('BMY', 'Healthcare', 'Bristol Myers Squibb'),
  ('AVGO', 'Technology', 'Broadcom'),
  ('BR', 'Industrials', 'Broadridge Financial Solutions'),
  ('BRO', 'Financials', 'Brown & Brown'),
  ('BLDR', 'Industrials', 'Builders FirstSource'),
  ('BG', 'Consumer Staples', 'Bunge Global'),
  ('BXP', 'Real Estate', 'BXP, Inc.'),
  ('CHRW', 'Industrials', 'C.H. Robinson'),
  ('CDNS', 'Technology', 'Cadence Design Systems'),
  ('CPT', 'Real Estate', 'Camden Property Trust'),
  ('CPB', 'Consumer Staples', 'Campbell''s Company (The)'),
  ('COF', 'Financials', 'Capital One'),
  ('CAH', 'Healthcare', 'Cardinal Health'),
  ('CCL', 'Consumer Discretionary', 'Carnival'),
  ('CARR', 'Industrials', 'Carrier Global'),
  ('CVNA', 'Consumer Discretionary', 'Carvana'),
  ('CASY', 'Consumer Staples', 'Casey''s'),
  ('CAT', 'Industrials', 'Caterpillar Inc.'),
  ('CBOE', 'Financials', 'Cboe Global Markets'),
  ('CBRE', 'Real Estate', 'CBRE Group'),
  ('CDW', 'Technology', 'CDW Corporation'),
  ('COR', 'Healthcare', 'Cencora'),
  ('CNC', 'Healthcare', 'Centene Corporation'),
  ('CNP', 'Utilities', 'CenterPoint Energy'),
  ('CF', 'Materials', 'CF Industries'),
  ('CRL', 'Healthcare', 'Charles River Laboratories'),
  ('SCHW', 'Financials', 'Charles Schwab Corporation'),
  ('CHTR', 'Communication Services', 'Charter Communications'),
  ('CVX', 'Energy', 'Chevron Corporation'),
  ('CMG', 'Consumer Discretionary', 'Chipotle Mexican Grill'),
  ('CB', 'Financials', 'Chubb Limited'),
  ('CHD', 'Consumer Staples', 'Church & Dwight'),
  ('CIEN', 'Technology', 'Ciena'),
  ('CI', 'Healthcare', 'Cigna'),
  ('CINF', 'Financials', 'Cincinnati Financial'),
  ('CTAS', 'Industrials', 'Cintas'),
  ('CSCO', 'Technology', 'Cisco'),
  ('C', 'Financials', 'Citigroup'),
  ('CFG', 'Financials', 'Citizens Financial Group'),
  ('CLX', 'Consumer Staples', 'Clorox'),
  ('CME', 'Financials', 'CME Group'),
  ('CMS', 'Utilities', 'CMS Energy'),
  ('KO', 'Consumer Staples', 'Coca-Cola Company (The)'),
  ('CTSH', 'Technology', 'Cognizant'),
  ('COHR', 'Technology', 'Coherent Corp.'),
  ('COIN', 'Financials', 'Coinbase'),
  ('CL', 'Consumer Staples', 'Colgate-Palmolive'),
  ('CMCSA', 'Communication Services', 'Comcast'),
  ('FIX', 'Industrials', 'Comfort Systems USA'),
  ('CAG', 'Consumer Staples', 'Conagra Brands'),
  ('COP', 'Energy', 'ConocoPhillips'),
  ('ED', 'Utilities', 'Consolidated Edison'),
  ('STZ', 'Consumer Staples', 'Constellation Brands'),
  ('CEG', 'Utilities', 'Constellation Energy'),
  ('COO', 'Healthcare', 'Cooper Companies (The)'),
  ('CPRT', 'Industrials', 'Copart'),
  ('GLW', 'Technology', 'Corning Inc.'),
  ('CPAY', 'Financials', 'Corpay'),
  ('CTVA', 'Materials', 'Corteva'),
  ('CSGP', 'Real Estate', 'CoStar Group'),
  ('COST', 'Consumer Staples', 'Costco'),
  ('CRH', 'Materials', 'CRH plc'),
  ('CRWD', 'Technology', 'CrowdStrike'),
  ('CCI', 'Real Estate', 'Crown Castle'),
  ('CSX', 'Industrials', 'CSX Corporation'),
  ('CMI', 'Industrials', 'Cummins'),
  ('CVS', 'Healthcare', 'CVS Health'),
  ('DHR', 'Healthcare', 'Danaher Corporation'),
  ('DRI', 'Consumer Discretionary', 'Darden Restaurants'),
  ('DDOG', 'Technology', 'Datadog'),
  ('DVA', 'Healthcare', 'DaVita'),
  ('DECK', 'Consumer Discretionary', 'Deckers Brands'),
  ('DE', 'Industrials', 'Deere & Company'),
  ('DELL', 'Technology', 'Dell Technologies'),
  ('DAL', 'Industrials', 'Delta Air Lines'),
  ('DVN', 'Energy', 'Devon Energy'),
  ('DXCM', 'Healthcare', 'Dexcom'),
  ('FANG', 'Energy', 'Diamondback Energy'),
  ('DLR', 'Real Estate', 'Digital Realty'),
  ('DG', 'Consumer Staples', 'Dollar General'),
  ('DLTR', 'Consumer Staples', 'Dollar Tree'),
  ('D', 'Utilities', 'Dominion Energy'),
  ('DPZ', 'Consumer Discretionary', 'Domino''s'),
  ('DASH', 'Consumer Discretionary', 'DoorDash'),
  ('DOV', 'Industrials', 'Dover Corporation'),
  ('DOW', 'Materials', 'Dow Inc.'),
  ('DHI', 'Consumer Discretionary', 'D. R. Horton'),
  ('DTE', 'Utilities', 'DTE Energy'),
  ('DUK', 'Utilities', 'Duke Energy'),
  ('DD', 'Materials', 'DuPont'),
  ('ETN', 'Industrials', 'Eaton Corporation'),
  ('EBAY', 'Consumer Discretionary', 'eBay Inc.'),
  ('SATS', 'Communication Services', 'EchoStar'),
  ('ECL', 'Materials', 'Ecolab'),
  ('EIX', 'Utilities', 'Edison International'),
  ('EW', 'Healthcare', 'Edwards Lifesciences'),
  ('EA', 'Communication Services', 'Electronic Arts'),
  ('ELV', 'Healthcare', 'Elevance Health'),
  ('EME', 'Industrials', 'Emcor'),
  ('EMR', 'Industrials', 'Emerson Electric'),
  ('ETR', 'Utilities', 'Entergy'),
  ('EOG', 'Energy', 'EOG Resources'),
  ('EPAM', 'Technology', 'EPAM Systems'),
  ('EQT', 'Energy', 'EQT Corporation'),
  ('EFX', 'Industrials', 'Equifax'),
  ('EQIX', 'Real Estate', 'Equinix'),
  ('EQR', 'Real Estate', 'Equity Residential'),
  ('ERIE', 'Financials', 'Erie Indemnity'),
  ('ESS', 'Real Estate', 'Essex Property Trust'),
  ('EL', 'Consumer Staples', 'Estée Lauder Companies (The)'),
  ('EG', 'Financials', 'Everest Group'),
  ('EVRG', 'Utilities', 'Evergy'),
  ('ES', 'Utilities', 'Eversource Energy'),
  ('EXC', 'Utilities', 'Exelon'),
  ('EXE', 'Energy', 'Expand Energy'),
  ('EXPE', 'Consumer Discretionary', 'Expedia Group'),
  ('EXPD', 'Industrials', 'Expeditors International'),
  ('EXR', 'Real Estate', 'Extra Space Storage'),
  ('XOM', 'Energy', 'ExxonMobil'),
  ('FFIV', 'Technology', 'F5, Inc.'),
  ('FDS', 'Financials', 'FactSet'),
  ('FICO', 'Technology', 'Fair Isaac'),
  ('FAST', 'Industrials', 'Fastenal'),
  ('FRT', 'Real Estate', 'Federal Realty Investment Trust'),
  ('FDX', 'Industrials', 'FedEx'),
  ('FIS', 'Financials', 'Fidelity National Information Services'),
  ('FITB', 'Financials', 'Fifth Third Bancorp'),
  ('FSLR', 'Technology', 'First Solar'),
  ('FE', 'Utilities', 'FirstEnergy'),
  ('FISV', 'Financials', 'Fiserv'),
  ('F', 'Consumer Discretionary', 'Ford Motor Company'),
  ('FTNT', 'Technology', 'Fortinet'),
  ('FTV', 'Industrials', 'Fortive'),
  ('FOXA', 'Communication Services', 'Fox Corporation (Class A)'),
  ('FOX', 'Communication Services', 'Fox Corporation (Class B)'),
  ('BEN', 'Financials', 'Franklin Resources'),
  ('FCX', 'Materials', 'Freeport-McMoRan'),
  ('GRMN', 'Consumer Discretionary', 'Garmin'),
  ('IT', 'Technology', 'Gartner'),
  ('GE', 'Industrials', 'GE Aerospace'),
  ('GEHC', 'Healthcare', 'GE HealthCare'),
  ('GEV', 'Industrials', 'GE Vernova'),
  ('GEN', 'Technology', 'Gen Digital'),
  ('GNRC', 'Industrials', 'Generac'),
  ('GD', 'Industrials', 'General Dynamics'),
  ('GIS', 'Consumer Staples', 'General Mills'),
  ('GM', 'Consumer Discretionary', 'General Motors'),
  ('GPC', 'Consumer Discretionary', 'Genuine Parts Company'),
  ('GILD', 'Healthcare', 'Gilead Sciences'),
  ('GPN', 'Financials', 'Global Payments'),
  ('GL', 'Financials', 'Globe Life'),
  ('GDDY', 'Technology', 'GoDaddy'),
  ('GS', 'Financials', 'Goldman Sachs'),
  ('HAL', 'Energy', 'Halliburton'),
  ('HIG', 'Financials', 'Hartford (The)'),
  ('HAS', 'Consumer Discretionary', 'Hasbro'),
  ('HCA', 'Healthcare', 'HCA Healthcare'),
  ('DOC', 'Real Estate', 'Healthpeak Properties'),
  ('HSIC', 'Healthcare', 'Henry Schein'),
  ('HSY', 'Consumer Staples', 'Hershey Company (The)'),
  ('HPE', 'Technology', 'Hewlett Packard Enterprise'),
  ('HLT', 'Consumer Discretionary', 'Hilton Worldwide'),
  ('HD', 'Consumer Discretionary', 'Home Depot (The)'),
  ('HON', 'Industrials', 'Honeywell'),
  ('HRL', 'Consumer Staples', 'Hormel Foods'),
  ('HST', 'Real Estate', 'Host Hotels & Resorts'),
  ('HWM', 'Industrials', 'Howmet Aerospace'),
  ('HPQ', 'Technology', 'HP Inc.'),
  ('HUBB', 'Industrials', 'Hubbell Incorporated'),
  ('HUM', 'Healthcare', 'Humana'),
  ('HBAN', 'Financials', 'Huntington Bancshares'),
  ('HII', 'Industrials', 'Huntington Ingalls Industries'),
  ('IBM', 'Technology', 'IBM'),
  ('IEX', 'Industrials', 'IDEX Corporation'),
  ('IDXX', 'Healthcare', 'Idexx Laboratories'),
  ('ITW', 'Industrials', 'Illinois Tool Works'),
  ('INCY', 'Healthcare', 'Incyte'),
  ('IR', 'Industrials', 'Ingersoll Rand'),
  ('PODD', 'Healthcare', 'Insulet Corporation'),
  ('INTC', 'Technology', 'Intel'),
  ('IBKR', 'Financials', 'Interactive Brokers'),
  ('ICE', 'Financials', 'Intercontinental Exchange'),
  ('IFF', 'Materials', 'International Flavors & Fragrances'),
  ('IP', 'Materials', 'International Paper'),
  ('INTU', 'Technology', 'Intuit'),
  ('ISRG', 'Healthcare', 'Intuitive Surgical'),
  ('IVZ', 'Financials', 'Invesco'),
  ('INVH', 'Real Estate', 'Invitation Homes'),
  ('IQV', 'Healthcare', 'IQVIA'),
  ('IRM', 'Real Estate', 'Iron Mountain'),
  ('JBHT', 'Industrials', 'J.B. Hunt'),
  ('JBL', 'Technology', 'Jabil'),
  ('JKHY', 'Financials', 'Jack Henry & Associates'),
  ('J', 'Industrials', 'Jacobs Solutions'),
  ('JNJ', 'Healthcare', 'Johnson & Johnson'),
  ('JCI', 'Industrials', 'Johnson Controls'),
  ('JPM', 'Financials', 'JPMorgan Chase'),
  ('KVUE', 'Consumer Staples', 'Kenvue'),
  ('KDP', 'Consumer Staples', 'Keurig Dr Pepper'),
  ('KEY', 'Financials', 'KeyCorp'),
  ('KEYS', 'Technology', 'Keysight Technologies'),
  ('KMB', 'Consumer Staples', 'Kimberly-Clark'),
  ('KIM', 'Real Estate', 'Kimco Realty'),
  ('KMI', 'Energy', 'Kinder Morgan'),
  ('KKR', 'Financials', 'KKR & Co.'),
  ('KLAC', 'Technology', 'KLA Corporation'),
  ('KHC', 'Consumer Staples', 'Kraft Heinz'),
  ('KR', 'Consumer Staples', 'Kroger'),
  ('LHX', 'Industrials', 'L3Harris'),
  ('LH', 'Healthcare', 'Labcorp'),
  ('LRCX', 'Technology', 'Lam Research'),
  ('LVS', 'Consumer Discretionary', 'Las Vegas Sands'),
  ('LDOS', 'Industrials', 'Leidos'),
  ('LEN', 'Consumer Discretionary', 'Lennar'),
  ('LII', 'Industrials', 'Lennox International'),
  ('LLY', 'Healthcare', 'Lilly (Eli)'),
  ('LIN', 'Materials', 'Linde plc'),
  ('LYV', 'Communication Services', 'Live Nation Entertainment'),
  ('LMT', 'Industrials', 'Lockheed Martin'),
  ('L', 'Financials', 'Loews Corporation'),
  ('LOW', 'Consumer Discretionary', 'Lowe''s'),
  ('LULU', 'Consumer Discretionary', 'Lululemon Athletica'),
  ('LITE', 'Technology', 'Lumentum'),
  ('LYB', 'Materials', 'LyondellBasell'),
  ('MTB', 'Financials', 'M&T Bank'),
  ('MPC', 'Energy', 'Marathon Petroleum'),
  ('MAR', 'Consumer Discretionary', 'Marriott International'),
  ('MRSH', 'Financials', 'Marsh McLennan'),
  ('MLM', 'Materials', 'Martin Marietta Materials'),
  ('MAS', 'Industrials', 'Masco'),
  ('MA', 'Financials', 'Mastercard'),
  ('MKC', 'Consumer Staples', 'McCormick & Company'),
  ('MCD', 'Consumer Discretionary', 'McDonald''s'),
  ('MCK', 'Healthcare', 'McKesson Corporation'),
  ('MDT', 'Healthcare', 'Medtronic'),
  ('MRK', 'Healthcare', 'Merck & Co.'),
  ('META', 'Communication Services', 'Meta Platforms'),
  ('MET', 'Financials', 'MetLife'),
  ('MTD', 'Healthcare', 'Mettler Toledo'),
  ('MGM', 'Consumer Discretionary', 'MGM Resorts'),
  ('MCHP', 'Technology', 'Microchip Technology'),
  ('MU', 'Technology', 'Micron Technology'),
  ('MSFT', 'Technology', 'Microsoft'),
  ('MAA', 'Real Estate', 'Mid-America Apartment Communities'),
  ('MRNA', 'Healthcare', 'Moderna'),
  ('TAP', 'Consumer Staples', 'Molson Coors Beverage Company'),
  ('MDLZ', 'Consumer Staples', 'Mondelez International'),
  ('MPWR', 'Technology', 'Monolithic Power Systems'),
  ('MNST', 'Consumer Staples', 'Monster Beverage'),
  ('MCO', 'Financials', 'Moody''s Corporation'),
  ('MS', 'Financials', 'Morgan Stanley'),
  ('MOS', 'Materials', 'Mosaic Company (The)'),
  ('MSI', 'Technology', 'Motorola Solutions'),
  ('MSCI', 'Financials', 'MSCI Inc.'),
  ('NDAQ', 'Financials', 'Nasdaq, Inc.'),
  ('NTAP', 'Technology', 'NetApp'),
  ('NFLX', 'Communication Services', 'Netflix'),
  ('NEM', 'Materials', 'Newmont'),
  ('NWSA', 'Communication Services', 'News Corp (Class A)'),
  ('NWS', 'Communication Services', 'News Corp (Class B)'),
  ('NEE', 'Utilities', 'NextEra Energy'),
  ('NKE', 'Consumer Discretionary', 'Nike, Inc.'),
  ('NI', 'Utilities', 'NiSource'),
  ('NDSN', 'Industrials', 'Nordson Corporation'),
  ('NSC', 'Industrials', 'Norfolk Southern'),
  ('NTRS', 'Financials', 'Northern Trust'),
  ('NOC', 'Industrials', 'Northrop Grumman'),
  ('NCLH', 'Consumer Discretionary', 'Norwegian Cruise Line Holdings'),
  ('NRG', 'Utilities', 'NRG Energy'),
  ('NUE', 'Materials', 'Nucor'),
  ('NVDA', 'Technology', 'Nvidia'),
  ('NVR', 'Consumer Discretionary', 'NVR, Inc.'),
  ('NXPI', 'Technology', 'NXP Semiconductors'),
  ('ORLY', 'Consumer Discretionary', 'O''Reilly Automotive'),
  ('OXY', 'Energy', 'Occidental Petroleum'),
  ('ODFL', 'Industrials', 'Old Dominion'),
  ('OMC', 'Communication Services', 'Omnicom Group'),
  ('ON', 'Technology', 'ON Semiconductor'),
  ('OKE', 'Energy', 'Oneok'),
  ('ORCL', 'Technology', 'Oracle Corporation'),
  ('OTIS', 'Industrials', 'Otis Worldwide'),
  ('PCAR', 'Industrials', 'Paccar'),
  ('PKG', 'Materials', 'Packaging Corporation of America'),
  ('PLTR', 'Technology', 'Palantir Technologies'),
  ('PANW', 'Technology', 'Palo Alto Networks'),
  ('PSKY', 'Communication Services', 'Paramount Skydance Corporation'),
  ('PH', 'Industrials', 'Parker Hannifin'),
  ('PAYX', 'Industrials', 'Paychex'),
  ('PYPL', 'Financials', 'PayPal'),
  ('PNR', 'Industrials', 'Pentair'),
  ('PEP', 'Consumer Staples', 'PepsiCo'),
  ('PFE', 'Healthcare', 'Pfizer'),
  ('PCG', 'Utilities', 'PG&E Corporation'),
  ('PM', 'Consumer Staples', 'Philip Morris International'),
  ('PSX', 'Energy', 'Phillips 66'),
  ('PNW', 'Utilities', 'Pinnacle West Capital'),
  ('PNC', 'Financials', 'PNC Financial Services'),
  ('POOL', 'Consumer Discretionary', 'Pool Corporation'),
  ('PPG', 'Materials', 'PPG Industries'),
  ('PPL', 'Utilities', 'PPL Corporation'),
  ('PFG', 'Financials', 'Principal Financial Group'),
  ('PG', 'Consumer Staples', 'Procter & Gamble'),
  ('PGR', 'Financials', 'Progressive Corporation'),
  ('PLD', 'Real Estate', 'Prologis'),
  ('PRU', 'Financials', 'Prudential Financial'),
  ('PEG', 'Utilities', 'Public Service Enterprise Group'),
  ('PTC', 'Technology', 'PTC Inc.'),
  ('PSA', 'Real Estate', 'Public Storage'),
  ('PHM', 'Consumer Discretionary', 'PulteGroup'),
  ('PWR', 'Industrials', 'Quanta Services'),
  ('QCOM', 'Technology', 'Qualcomm'),
  ('DGX', 'Healthcare', 'Quest Diagnostics'),
  ('Q', 'Technology', 'Qnity Electronics'),
  ('RL', 'Consumer Discretionary', 'Ralph Lauren Corporation'),
  ('RJF', 'Financials', 'Raymond James Financial'),
  ('RTX', 'Industrials', 'RTX Corporation'),
  ('O', 'Real Estate', 'Realty Income'),
  ('REG', 'Real Estate', 'Regency Centers'),
  ('REGN', 'Healthcare', 'Regeneron Pharmaceuticals'),
  ('RF', 'Financials', 'Regions Financial Corporation'),
  ('RSG', 'Industrials', 'Republic Services'),
  ('RMD', 'Healthcare', 'ResMed'),
  ('RVTY', 'Healthcare', 'Revvity'),
  ('HOOD', 'Financials', 'Robinhood Markets'),
  ('ROK', 'Industrials', 'Rockwell Automation'),
  ('ROL', 'Industrials', 'Rollins, Inc.'),
  ('ROP', 'Technology', 'Roper Technologies'),
  ('ROST', 'Consumer Discretionary', 'Ross Stores'),
  ('RCL', 'Consumer Discretionary', 'Royal Caribbean Group'),
  ('SPGI', 'Financials', 'S&P Global'),
  ('CRM', 'Technology', 'Salesforce'),
  ('SNDK', 'Technology', 'Sandisk'),
  ('SBAC', 'Real Estate', 'SBA Communications'),
  ('SLB', 'Energy', 'Schlumberger'),
  ('STX', 'Technology', 'Seagate Technology'),
  ('SRE', 'Utilities', 'Sempra'),
  ('NOW', 'Technology', 'ServiceNow'),
  ('SHW', 'Materials', 'Sherwin-Williams'),
  ('SPG', 'Real Estate', 'Simon Property Group'),
  ('SWKS', 'Technology', 'Skyworks Solutions'),
  ('SJM', 'Consumer Staples', 'J.M. Smucker Company (The)'),
  ('SW', 'Materials', 'Smurfit Westrock'),
  ('SNA', 'Industrials', 'Snap-on'),
  ('SOLV', 'Healthcare', 'Solventum'),
  ('SO', 'Utilities', 'Southern Company'),
  ('LUV', 'Industrials', 'Southwest Airlines'),
  ('SWK', 'Industrials', 'Stanley Black & Decker'),
  ('SBUX', 'Consumer Discretionary', 'Starbucks'),
  ('STT', 'Financials', 'State Street Corporation'),
  ('STLD', 'Materials', 'Steel Dynamics'),
  ('STE', 'Healthcare', 'Steris'),
  ('SYK', 'Healthcare', 'Stryker Corporation'),
  ('SMCI', 'Technology', 'Supermicro'),
  ('SYF', 'Financials', 'Synchrony Financial'),
  ('SNPS', 'Technology', 'Synopsys'),
  ('SYY', 'Consumer Staples', 'Sysco'),
  ('TMUS', 'Communication Services', 'T-Mobile US'),
  ('TROW', 'Financials', 'T. Rowe Price'),
  ('TTWO', 'Communication Services', 'Take-Two Interactive'),
  ('TPR', 'Consumer Discretionary', 'Tapestry, Inc.'),
  ('TRGP', 'Energy', 'Targa Resources'),
  ('TGT', 'Consumer Staples', 'Target Corporation'),
  ('TEL', 'Technology', 'TE Connectivity'),
  ('TDY', 'Technology', 'Teledyne Technologies'),
  ('TER', 'Technology', 'Teradyne'),
  ('TSLA', 'Consumer Discretionary', 'Tesla, Inc.'),
  ('TXN', 'Technology', 'Texas Instruments'),
  ('TPL', 'Energy', 'Texas Pacific Land Corporation'),
  ('TXT', 'Industrials', 'Textron'),
  ('TMO', 'Healthcare', 'Thermo Fisher Scientific'),
  ('TJX', 'Consumer Discretionary', 'TJX Companies'),
  ('TKO', 'Communication Services', 'TKO Group Holdings'),
  ('TTD', 'Communication Services', 'Trade Desk (The)'),
  ('TSCO', 'Consumer Discretionary', 'Tractor Supply'),
  ('TT', 'Industrials', 'Trane Technologies'),
  ('TDG', 'Industrials', 'TransDigm Group'),
  ('TRV', 'Financials', 'Travelers Companies (The)'),
  ('TRMB', 'Technology', 'Trimble Inc.'),
  ('TFC', 'Financials', 'Truist Financial'),
  ('TYL', 'Technology', 'Tyler Technologies'),
  ('TSN', 'Consumer Staples', 'Tyson Foods'),
  ('USB', 'Financials', 'U.S. Bancorp'),
  ('UBER', 'Industrials', 'Uber'),
  ('UDR', 'Real Estate', 'UDR, Inc.'),
  ('ULTA', 'Consumer Discretionary', 'Ulta Beauty'),
  ('UNP', 'Industrials', 'Union Pacific Corporation'),
  ('UAL', 'Industrials', 'United Airlines Holdings'),
  ('UPS', 'Industrials', 'United Parcel Service'),
  ('URI', 'Industrials', 'United Rentals'),
  ('UNH', 'Healthcare', 'UnitedHealth Group'),
  ('UHS', 'Healthcare', 'Universal Health Services'),
  ('VLO', 'Energy', 'Valero Energy'),
  ('VEEV', 'Healthcare', 'Veeva Systems'),
  ('VTR', 'Real Estate', 'Ventas'),
  ('VLTO', 'Industrials', 'Veralto'),
  ('VRSN', 'Technology', 'Verisign'),
  ('VRSK', 'Industrials', 'Verisk Analytics'),
  ('VZ', 'Communication Services', 'Verizon'),
  ('VRTX', 'Healthcare', 'Vertex Pharmaceuticals'),
  ('VRT', 'Industrials', 'Vertiv'),
  ('VTRS', 'Healthcare', 'Viatris'),
  ('VICI', 'Real Estate', 'Vici Properties'),
  ('V', 'Financials', 'Visa Inc.'),
  ('VST', 'Utilities', 'Vistra Corp.'),
  ('VMC', 'Materials', 'Vulcan Materials Company'),
  ('WRB', 'Financials', 'W. R. Berkley Corporation'),
  ('GWW', 'Industrials', 'W. W. Grainger'),
  ('WAB', 'Industrials', 'Wabtec'),
  ('WMT', 'Consumer Staples', 'Walmart'),
  ('DIS', 'Communication Services', 'Walt Disney Company (The)'),
  ('WBD', 'Communication Services', 'Warner Bros. Discovery'),
  ('WM', 'Industrials', 'Waste Management'),
  ('WAT', 'Healthcare', 'Waters Corporation'),
  ('WEC', 'Utilities', 'WEC Energy Group'),
  ('WFC', 'Financials', 'Wells Fargo'),
  ('WELL', 'Real Estate', 'Welltower'),
  ('WST', 'Healthcare', 'West Pharmaceutical Services'),
  ('WDC', 'Technology', 'Western Digital'),
  ('WY', 'Real Estate', 'Weyerhaeuser'),
  ('WSM', 'Consumer Discretionary', 'Williams-Sonoma, Inc.'),
  ('WMB', 'Energy', 'Williams Companies'),
  ('WTW', 'Financials', 'Willis Towers Watson'),
  ('WDAY', 'Technology', 'Workday, Inc.'),
  ('WYNN', 'Consumer Discretionary', 'Wynn Resorts'),
  ('XEL', 'Utilities', 'Xcel Energy'),
  ('XYL', 'Industrials', 'Xylem Inc.'),
  ('YUM', 'Consumer Discretionary', 'Yum! Brands'),
  ('ZBRA', 'Technology', 'Zebra Technologies'),
  ('ZBH', 'Healthcare', 'Zimmer Biomet'),
  ('ZTS', 'Healthcare', 'Zoetis'),
  ('BRK', 'Financials', 'Berkshire Hathaway Inc.')
ON CONFLICT (symbol) DO NOTHING;
